name: Deploy Azure Function (.NET 10)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: iscream
  DOTNET_VERSION: '10.0.x'
  PROJECT_PATH: 'backend/backend.csproj'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o publish_output

      # tạo zip deploy package
      - name: Zip package
        run: |
          cd publish_output
          zip -r ../app.zip .

      # Deploy bằng webapps-deploy thay vì functions-action
      - name: Deploy to Azure Function (zip)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: app.zip
